version: '3.8'


services:

  db:
    container_name: db-beers
    build: ./sql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'beer'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'

  api:
    container_name: api-beers
    build: ./api
    depends_on:
      - db
    ports:
      - '81:5000'
    restart: unless-stopped







